apiVersion: stork.libopenstorage.org/v1alpha1
kind: MigrationSchedule
metadata:
  name: mysqlmigrationschedule-mysql
  namespace: pwx-test-app1
spec:
  template:
    spec:
      # This should be the name of the cluster pair created above
      clusterPair: secondary-cluster
      # If set to false this will migrate only the Portworx volumes. No PVCs, apps, etc will be migrated
      includeResources: true
      # If set to false, the deployments and stateful set replicas will be set to 0 on the destination.
      # If set to true, the deployments and stateful sets will start running once the migration is done
      # There will be an annotation with "stork.openstorage.org/migrationReplicas" on the destinationto store the replica count from the source.
      startApplications: true
       # If set to false, the volumes will not be migrated
      includeVolumes: true
      # List of namespaces to migrate
      namespaces:
      - pwx-test-app1
  schedulePolicyName: policy-mysql
