variable "app-instances-ip" {}
variable "gitaly-instances-ip" {}
variable "praefect-instances-ip" {}
variable "mon-instances-ip" {}
variable "gitlab-lb-url" {}
variable "gitlab_version" {}
variable "praefect_internal_token" {}
variable "praefect_external_token" {}
variable "gitlab_root_password" {}
variable "grafana_admin_password" {}
variable "praefect-database-endpoint" {}
variable "praefect-db-username" {}
variable "praefect-db-password" {}
variable "praefect-db-name" {}
variable "gitlab-gui" {}
variable "gitlab-pages" {}
variable "gitlab-registry" {}
variable "gitlab-region" {}
variable "gitlab-database-endpoint" {}
variable "gitlab-db-name" {}
variable "gitlab-db-username" {}
variable "gitlab-db-password" {}
variable "elasticache_endpoint" {}
variable "s3-registry" {}
variable "s3-backup" {}
variable "s3-artifacts" {}
variable "s3-uploads" {}
variable "s3-diffs" {}
variable "s3-lfs" {}
variable "monitoring_elb" {}
variable "praefect-lb-url" {}
