variable "app_instances_ip" {}
variable "gitaly_instances_ip" {}
variable "praefect_instances_ip" {}
variable "mon_instances_ip" {}
variable "gitlab_lb_url" {}
variable "gitlab_version" {}
variable "praefect_internal_token" {}
variable "praefect_external_token" {}
variable "gitlab_root_password" {}
variable "grafana_admin_password" {}
variable "praefect_database_endpoint" {}
variable "praefect_db_username" {}
variable "praefect_db_password" {}
variable "praefect_db_name" {}
variable "gitlab_gui" {}
variable "gitlab_pages" {}
variable "gitlab_registry" {}
variable "gitlab_region" {}
variable "gitlab_database_endpoint" {}
variable "gitlab_db_name" {}
variable "gitlab_db_username" {}
variable "gitlab_db_password" {}
variable "elasticache_endpoint" {}
variable "s3_registry" {}
variable "s3_backup" {}
variable "s3_artifacts" {}
variable "s3_uploads" {}
variable "s3_diffs" {}
variable "s3_lfs" {}
variable "monitoring_elb" {}
variable "praefect_lb_url" {}
