apiVersion: stork.libopenstorage.org/v1alpha1
kind: ClusterPair
metadata:
  creationTimestamp: null
  name: secondary-cluster
  namespace: pwx-test-app1
spec:
  config:
    clusters:
      secondary-cluster:
        LocationOfOrigin: /tmp/admin-secondary.kubeconfig
        certificate-authority-data: {{cert_second_cluster}} 
        server: {{server_second_cluster}} 
    contexts:
      secondary-cluster:
        LocationOfOrigin: /tmp/admin-secondary.kubeconfig
        cluster: secondary-cluster
        user: k8s-admin
    current-context: secondary-cluster
    preferences: {}
    users:
      k8s-admin:
        LocationOfOrigin: /tmp/admin-secondary.kubeconfig
        token: '{{k8s_token}}'
  options:
    ip:  '{{second_pwx_external_svc}}'
    port:  '9001'
    token: '{{second_pwx_cluster_token}}'
    mode: DisasterRecovery
