apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: ooo-mysql
  name: mysql
  namespace: pwx-test-app1
spec:
  podManagementPolicy: OrderedReady
  replicas: 3
  selector:
    matchLabels:
      app: ooo-mysql
  serviceName: mysql
  template:
    metadata:
      labels:
        app: ooo-mysql
        statefulset: mysql
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - ooo-mysql
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: MYSQL_USER
            value: admin
          - name: MYSQL_PASSWORD
            value: glonti
          - name: MYSQL_DATABASE
            value: controldb
          - name: MYSQL_ROOT_PASSWORD
            value: glonti
          - name: GALERA_PETSET_NAME
            value: mysql
        image: quay.io/ooo-openstack/mysql:latest
        imagePullPolicy: Always
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql
          protocol: TCP
        - containerPort: 4444
          name: sst
          protocol: TCP
        - containerPort: 4567
          name: replication
          protocol: TCP
        - containerPort: 4568
          name: ist
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /usr/share/container-scripts/mysql/readiness-probe.sh
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "1"
            memory: 500Mi
          requests:
            cpu: "500m"
            memory: 300Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: datadir
            subPath: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 27
      serviceAccount: mysql-sa
      serviceAccountName: mysql-sa
      terminationGracePeriodSeconds: 30
  updateStrategy:
    type: OnDelete
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: px-db
      resources:
        requests:
          storage: "20Gi"
