- hosts: app
  become: true
  tasks:
  - name: Create user for redis-exporter
    ansible.builtin.user:
      name: gitlab-redis
      state: present
  - name: Copy application.rb
    template:
      src: application.rb.j2
      dest: /etc/gitlab/gitlab.rb
  - name: Create gitlab-secrets.json
    copy:
      src: "files/gitlab-secrets.json"
      dest: /etc/gitlab/gitlab-secrets.json
      owner: root
      group: root
      mode: 0600
  - name: gitlab-ctl reconfigure
    shell: (gitlab-ctl reconfigure || gitlab-ctl reconfigure)
  - name: Run DB migrations on primary region app node
    shell: gitlab-rake gitlab:db:configure
  - name: gitlab-ctl restart
    shell: gitlab-ctl restart
  - blockinfile:
      path: /etc/ssh/sshd_config
      block: |
        Match User git
          AuthorizedKeysCommand /opt/gitlab/embedded/service/gitlab-shell/bin/gitlab-shell-authorized-keys-check git %u %k
          AuthorizedKeysCommandUser git
        Match all
    notify: restart sshd

#  - name: Mount AWS EFS for Gitlab Pages
#    mount:
#      path: /var/opt/gitlab/gitlab-rails/shared/pages
#      src: "{{ efs_id[ansible_facts.ec2_placement_region] }}:/"
#      fstype: efs
#      opts: tls,iam
#      state: mounted
#    notify: restart Gitlab Pages

  handlers:
  - name: restart sshd
    service:
      name: sshd
      state: restarted

#  - name: restart Gitlab Pages
#    shell: gitlab-ctl restart gitlab-pages
