- hosts: gitaly
  become: true
  tasks:
  - block:
    - name: Create Linux group for Gitaly
      ansible.builtin.group:
        name: git
        state: present
        gid: 932
    - name: Create Linux user for Gitaly
      ansible.builtin.user:
        name: git
        uid: 935
        group: git
        home: /var/opt/gitlab
        shell: /bin/sh
    - name: Create filesystem on Gitaly volume
      filesystem:
        fstype: ext4
        dev: /dev/nvme1n1
    - name: Mount Gitaly volume
      mount:
        path: /gitaly
        src: /dev/nvme1n1
        state: mounted
        fstype: ext4
    ignore_errors: yes
  - name: Create gitlab-secrets.json
    copy:
      src: "files/gitlab-secrets.json"
      dest: /etc/gitlab/gitlab-secrets.json
      owner: root
      group: root
      mode: 0600
    notify: gitlab-ctl reconfigure and restart
  - name: Copy gitaly.rb
    template:
      src: gitaly.rb.j2
      dest: /etc/gitlab/gitlab.rb
    notify: gitlab-ctl reconfigure and restart

  handlers:
  - name: gitlab-ctl reconfigure and restart
    shell: (gitlab-ctl reconfigure || gitlab-ctl reconfigure) && gitlab-ctl restart
