- hosts: praefect
  become: true
  tasks:
  - name: Copy praefect.rb
    template:
      src: praefect.rb.j2
      dest: /etc/gitlab/gitlab.rb
    notify: gitlab-ctl reconfigure and restart

  handlers:
  - name: gitlab-ctl reconfigure and restart
    shell: gitlab-ctl reconfigure && gitlab-ctl restart
