- hosts: mon
  become: true
  tasks:
  - block:
    - amazon.aws.ec2_metadata_facts:
    - name: Create Linux group for Prometheus
      ansible.builtin.group:
        state: present
        name: gitlab-prometheus
        gid: 930
    - name: Create Linux user for Prometheus
      ansible.builtin.user:
        state: present
        name: gitlab-prometheus
        uid: 933
        group: gitlab-prometheus
        home: /var/opt/gitlab/prometheus
        shell: /bin/sh
    - name: Create filesystem on monitoring volume
      filesystem:
        fstype: ext4
        dev: /dev/nvme1n1
    - name: Create Prometheus data directory
      ansible.builtin.file:
        path: /var/opt/gitlab/prometheus/data
        state: directory
        owner: gitlab-prometheus
        group: gitlab-prometheus
        recurse: yes
    ignore_errors: yes
  - name: Mount monitoring volume
    mount:
      path: /var/opt/gitlab/prometheus/data
      src: /dev/nvme1n1
      state: mounted
      fstype: ext4
    notify: gitlab-ctl reconfigure and restart
  - name: Create gitlab-secrets.json
    copy:
      src: "files/gitlab-secrets.json"
      dest: /etc/gitlab/gitlab-secrets.json
      owner: root
      group: root
      mode: 0600
    notify: gitlab-ctl reconfigure and restart

  - name: Copy monitoring.rb
    template:
      src: monitoring.rb.j2
      dest: /etc/gitlab/gitlab.rb
    notify: gitlab-ctl reconfigure and restart

  handlers:
  - name: gitlab-ctl reconfigure and restart
    shell: (gitlab-ctl reconfigure || gitlab-ctl reconfigure) && gitlab-ctl restart
