- hosts: praefect
  become: true
  tasks:
  - name: Create gitlab-secrets.json
    copy:
      src: "files/gitlab-secrets.json"
      dest: /etc/gitlab/gitlab-secrets.json
      owner: root
      group: root
      mode: 0600
    notify: gitlab-ctl reconfigure and restart

  - name: Copy praefect.rb
    template:
      src: praefect.rb.j2
      dest: /etc/gitlab/gitlab.rb
    notify: gitlab-ctl reconfigure and restart

  handlers:
  - name: gitlab-ctl reconfigure and restart
    shell: (gitlab-ctl reconfigure || gitlab-ctl reconfigure) && gitlab-ctl restart
