- hosts: all
  become: true
  tasks:
  - yum_repository:
      name: gitlab-ee
      description: Gitlab EE repo
      baseurl: https://packages.gitlab.com/gitlab/gitlab-ee/el/8/$basearch
      gpgcheck: yes
      gpgkey:
      - https://packages.gitlab.com/gitlab/gitlab-ee/gpgkey
      - https://packages.gitlab.com/gitlab/gitlab-ee/gpgkey/gitlab-gitlab-ee-3D645A26AB9FBD22.pub.gpg
  - file:
      path: /var/opt/gitlab
      state: directory
  - file:
      path: /var/opt/gitlab/bootstrapped
      state: touch
  - yum:
      name: "gitlab-ee-{{ gitlab_version }}"
